# Generated by Django 4.0.1 on 2022-02-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_slug',
        ),
    ]
